/**
 * server/models/Customer.js
 * -------------------------
 * The customers collection — UC4, "Add a customer".
 *
 * Almost identical to Instructor: the same six demographic fields, defined
 * once in personFields.js and spread into both schemas. The two differences
 * are the ID prefix (C rather than I) and `classBalance`, which exists only
 * for customers.
 */

import mongoose from 'mongoose';
import { personFields } from './personFields.js';

const customerSchema = new mongoose.Schema(
  {
    // UC4: "C00123". Generated by the controller, never typed by the manager.
    // The prefix is what distinguishes a customer ID from an instructor ID.
    customerId: {
      type: String,
      required: true,
      unique: true,
      immutable: true,
    },

    // firstName, lastName, address, phone, email, preferredContact
    ...personFields(),

    /**
     * How many classes this customer has left to use.
     *
     * UC4 requires it to start at 0. It is not edited directly: UC5 (record a
     * sale) increases it when a package is bought, and UC6 (record
     * attendance) decreases it on check-in.
     *
     * There is deliberately NO `min: 0` here. UC6 step 8 requires that an
     * instructor be allowed to check in a customer who has run out, saving a
     * negative balance to be resolved later. A minimum would make that
     * legitimate case impossible.
     */
    classBalance: {
      type: Number,
      required: true,
      default: 0,
    },

    // See decision 9: Part 2 deactivates rather than deletes.
    active: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

// A getter with no stored field behind it (Java analogy: a computed getter).
customerSchema.virtual('fullName').get(function () {
  return `${this.firstName} ${this.lastName}`;
});

customerSchema.set('toJSON', { virtuals: true });
customerSchema.set('toObject', { virtuals: true });

// UC4 step 2 looks a customer up by name on every save, so that query is
// indexed rather than left to scan the whole collection.
customerSchema.index({ lastName: 1, firstName: 1 });

export default mongoose.model('Customer', customerSchema);
