/**
 * server/models/Package.js
 * ------------------------
 * The packages collection — UC3, "Add a package".
 *
 * A package is what the studio sells: a number of classes, valid between two
 * dates, at a price. The real price list (Fig. 2 of the requirements) is:
 *
 *     Single Class (Drop in)                          $20
 *     4 Class Pass    - validity one month            $70
 *     10 Class Pass   - validity three months        $140
 *     3 Months Unlimited                             $400
 *     Seniors (62 and older):
 *     4 Class Pass    - validity one month            $60
 *     10 Class Pass   - validity three months        $120
 *     3 Months Unlimited                             $360
 *
 * Those seven rows are what `npm run seed:packages` inserts, and they are the
 * reason the schema looks the way it does.
 */

import mongoose from 'mongoose';

// The class counts the studio actually sells. "Unlimited" is deliberately NOT
// in this list: it is represented by the `unlimited` flag below, not by a
// magic number. See design decision 4.
export const ALLOWED_CLASS_COUNTS = [1, 4, 10];

const packageSchema = new mongoose.Schema(
  {
    // "P00001". Generated by the controller (UC3 step 2), never typed in.
    packageId: {
      type: String,
      required: true,
      unique: true,
      immutable: true,
    },

    name: {
      type: String,
      required: [true, 'Package name is required.'],
      trim: true,
      maxlength: [80, 'Package name cannot exceed 80 characters.'],
    },

    /**
     * Who the package is priced for. The studio discounts every package for
     * seniors, which Fig. 2 defines as 62 and older. The age itself is not
     * stored anywhere yet — no use case asks for a date of birth — so this is
     * a pricing category the manager chooses, not something derived.
     */
    category: {
      type: String,
      required: [true, 'Please choose a package category.'],
      enum: {
        values: ['General', 'Senior'],
        message: 'Category must be either General or Senior.',
      },
    },

    /**
     * True for the 3-month unlimited pass.
     *
     * Design decision 4. The alternative was a sentinel such as
     * numClasses = -1, which reads as a bug and forces a special case into
     * every balance check and every balance display. A boolean says what is
     * actually meant, and entitlement for an unlimited package is decided by
     * the validity dates rather than by counting down a balance.
     */
    unlimited: {
      type: Boolean,
      required: true,
      default: false,
    },

    /**
     * How many classes the package buys: 1, 4 or 10.
     *
     * `null` when `unlimited` is true. Note that `required` here is a
     * FUNCTION, not `true`: Mongoose calls it with the document as `this`, so
     * the field is mandatory for a counted package and optional for an
     * unlimited one. A plain `required: true` would make the unlimited pass
     * impossible to save.
     */
    numClasses: {
      type: Number,
      default: null,
      required: [
        function () {
          return !this.unlimited;
        },
        'Please choose how many classes this package includes.',
      ],
      validate: {
        validator: function (value) {
          // An unlimited package must not carry a count, and a counted
          // package must use one of the counts the studio actually sells.
          if (this.unlimited) return value === null || value === undefined;
          return ALLOWED_CLASS_COUNTS.includes(value);
        },
        message: 'Number of classes must be 1, 4 or 10, or the package must be unlimited.',
      },
    },

    /**
     * Which classes the package admits its holder to.
     * A 'General' package works for any class marked General; a 'Special'
     * package admits only classes marked Special, e.g. Yoga with Weights.
     */
    classType: {
      type: String,
      required: [true, 'Please choose a class type.'],
      enum: {
        values: ['General', 'Special'],
        message: 'Class type must be either General or Special.',
      },
    },

    startDate: {
      type: Date,
      required: [true, 'Start date is required.'],
    },

    endDate: {
      type: Date,
      required: [true, 'End date is required.'],
      validate: {
        // `this` is the document being saved, so the end date can be compared
        // against the start date on the same document. A package that expires
        // before it begins can never be sold, so it is rejected at the schema.
        validator: function (value) {
          return !this.startDate || value > this.startDate;
        },
        message: 'End date must be after the start date.',
      },
    },

    /**
     * Price in US dollars.
     *
     * Stored as a Number for simplicity, which is the conventional choice for
     * a project of this size. Worth knowing the trade-off: floating point
     * cannot represent every decimal exactly, so a production billing system
     * would store cents as an integer instead. Nothing here multiplies or
     * compounds prices, so the risk does not arise; UC5 compares an amount
     * paid against this value, which is an equality check on two values that
     * came from the same source.
     */
    price: {
      type: Number,
      required: [true, 'Price is required.'],
      min: [0, 'Price cannot be negative.'],
    },

    // See decision 9: Part 2 deactivates rather than deletes, because a
    // package that has sales against it must not simply vanish.
    active: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

/**
 * A human-readable description of what the package includes, e.g.
 * "Unlimited classes" or "10 classes". Derived rather than stored, so it can
 * never disagree with the fields it is built from.
 */
packageSchema.virtual('classesLabel').get(function () {
  if (this.unlimited) return 'Unlimited';
  return `${this.numClasses} ${this.numClasses === 1 ? 'class' : 'classes'}`;
});

/**
 * Whether the package is currently within its validity window. UC5 will need
 * this when deciding which packages a manager may sell today.
 */
packageSchema.virtual('isCurrent').get(function () {
  const now = new Date();
  return this.startDate <= now && this.endDate >= now;
});

packageSchema.set('toJSON', { virtuals: true });
packageSchema.set('toObject', { virtuals: true });

// The package list is filtered by category and class type when recording a
// sale, so those two fields are indexed together.
packageSchema.index({ category: 1, classType: 1 });

export default mongoose.model('Package', packageSchema);
