/**
 * server/controllers/instructorController.js
 * ------------------------------------------
 * The business rules for UC1, "Add an instructor".
 *
 * The route file says WHICH url runs WHICH function; this file is what those
 * functions do. Java analogy: routes are the @RequestMapping annotations,
 * this is the service class behind them.
 *
 * Every handler is `async` because every database call returns a Promise.
 * Express 5 catches errors thrown inside async handlers on its own and passes
 * them to middleware/errorHandler.js, so there is no try/catch here — an
 * important difference from Express 4, where an uncaught async error would
 * hang the request forever.
 */

import Instructor from '../models/Instructor.js';
import { generateId } from '../services/idGenerator.js';
import { sendMessage, welcomeMessage } from '../services/messaging.js';

/**
 * Find instructors already recorded under a given name.
 * UC1 steps 2-3: the form calls this BEFORE saving, and only if a match comes
 * back does the UI ask "someone with this name already exists, continue?".
 *
 * GET /api/instructors/check-name?firstName=Ann&lastName=Lee
 */
export async function checkInstructorName(req, res) {
  const { firstName = '', lastName = '' } = req.query;

  if (!firstName.trim() || !lastName.trim()) {
    return res.status(400).json({
      error: 'Missing name',
      message: 'Both first and last name are needed to check for duplicates.',
    });
  }

  // A plain === match would treat "ann lee" as a different person from
  // "Ann Lee". A case-insensitive exact-match regular expression avoids that.
  // `^...$` anchors it so "Ann" does not also match "Annabel".
  const matches = await Instructor.find({
    firstName: new RegExp(`^${escapeRegex(firstName.trim())}$`, 'i'),
    lastName: new RegExp(`^${escapeRegex(lastName.trim())}$`, 'i'),
  }).select('instructorId firstName lastName email');

  res.json({
    exists: matches.length > 0,
    count: matches.length,
    matches,
  });
}

/**
 * Create an instructor. UC1 steps 4-8.
 *
 * POST /api/instructors
 * Body: firstName, lastName, address, phone, email, preferredContact,
 *       plus confirmDuplicate: true when the manager has already been warned.
 */
export async function createInstructor(req, res) {
  const {
    firstName,
    lastName,
    address,
    phone,
    email,
    preferredContact,
    confirmDuplicate = false,
  } = req.body;

  // UC1 step 3, enforced on the server as well as in the UI. The client is
  // expected to have called check-name first, but a request can always arrive
  // without having done so, and the server is the only place a rule is real.
  if (!confirmDuplicate && firstName && lastName) {
    const duplicates = await Instructor.countDocuments({
      firstName: new RegExp(`^${escapeRegex(firstName.trim())}$`, 'i'),
      lastName: new RegExp(`^${escapeRegex(lastName.trim())}$`, 'i'),
    });

    if (duplicates > 0) {
      // 409 Conflict, not 400: the data is valid, it just needs confirming.
      // `requiresConfirmation` tells the React form to show the prompt rather
      // than a red validation error.
      return res.status(409).json({
        error: 'Duplicate name',
        requiresConfirmation: true,
        message:
          `${duplicates} instructor${duplicates > 1 ? 's are' : ' is'} already ` +
          `recorded as ${firstName} ${lastName}. Add this person anyway?`,
      });
    }
  }

  // Build the document in memory. `new Model(...)` does NOT touch the
  // database — nothing is saved until .save() is called further down.
  const instructor = new Instructor({
    firstName,
    lastName,
    address,
    phone,
    email,
    preferredContact,
  });

  // UC1 step 6: validate BEFORE generating an ID.
  //
  // Order matters here. Generating the ID first would consume a counter number
  // on every rejected submission, so a manager who mistypes twice would see
  // the next instructor saved as I00004 instead of I00002. Validating first
  // means a number is only ever handed out to a record that will be kept.
  //
  // instructorId is skipped because it is deliberately not set yet; every
  // other field is checked. A failure throws a ValidationError, which
  // errorHandler.js turns into a 400 carrying per-field messages the form
  // displays next to the offending input.
  await instructor.validate({ pathsToSkip: ['instructorId'] });

  // UC1 step 4: the ID is generated by the system, never supplied by the form.
  instructor.instructorId = await generateId('instructor');

  // UC1 step 7: now write it to MongoDB.
  await instructor.save();

  // UC1 step 8: confirmation on the instructor's preferred channel. Part 1
  // logs it and returns it so the UI can show exactly what would be sent.
  const notification = await sendMessage(
    instructor,
    welcomeMessage(instructor.firstName, instructor.instructorId, 'instructor')
  );

  // 201 Created is the correct status for "a new resource now exists".
  res.status(201).json({
    message: `Instructor ${instructor.instructorId} saved successfully.`,
    instructor,
    notification,
  });
}

/**
 * List instructors, newest first.
 * Not in the written UC1, but without it nothing that was saved is ever
 * visible. Decision #9: read views are in Part 1, edit and delete in Part 2.
 *
 * GET /api/instructors
 */
export async function listInstructors(req, res) {
  const instructors = await Instructor.find().sort({ createdAt: -1 });
  res.json({ count: instructors.length, instructors });
}

/**
 * Fetch one instructor by their human-readable ID.
 * GET /api/instructors/I00001
 */
export async function getInstructor(req, res) {
  const instructor = await Instructor.findOne({
    instructorId: req.params.instructorId.toUpperCase(),
  });

  if (!instructor) {
    return res.status(404).json({
      error: 'Not found',
      message: `No instructor with id ${req.params.instructorId}.`,
    });
  }

  res.json({ instructor });
}

/**
 * Escape characters that have a special meaning inside a regular expression.
 *
 * Without this, a name containing "." or "(" would be interpreted as a regex
 * operator instead of a literal character — wrong results at best, and at
 * worst a way for input to change what the query means.
 *
 * @param {string} text
 * @returns {string} text safe to embed in a RegExp
 */
function escapeRegex(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
