/**
 * server/controllers/packageController.js
 * ---------------------------------------
 * The business rules for UC3, "Add a package".
 *
 * UC3 is the simplest of the three Part 1 use cases: no duplicate check and
 * no branch. The manager enters the data, YogiTrack generates a package ID
 * and confirms. The complexity that does exist is in the schema — the
 * unlimited flag and the date-order rule — rather than here.
 */

import Package from '../models/Package.js';
import { generateId } from '../services/idGenerator.js';

/**
 * Create a package. UC3 steps 1-2.
 *
 * POST /api/packages
 * Body: name, category, unlimited, numClasses, classType,
 *       startDate, endDate, price
 */
export async function createPackage(req, res) {
  const {
    name,
    category,
    classType,
    startDate,
    endDate,
    price,
    unlimited = false,
    numClasses,
  } = req.body;

  // Build in memory; nothing is written until .save() below.
  //
  // numClasses is forced to null for an unlimited package rather than trusted
  // from the request. A body carrying both `unlimited: true` and
  // `numClasses: 10` is contradictory, and silently storing both would leave
  // a document that later code could read either way.
  const newPackage = new Package({
    name,
    category,
    classType,
    startDate,
    endDate,
    price,
    unlimited: Boolean(unlimited),
    numClasses: unlimited ? null : numClasses,
  });

  // Validate before the counter is touched, so a rejected form never consumes
  // an ID number. Same rule as UC1 and UC4; see design decision 15.
  await newPackage.validate({ pathsToSkip: ['packageId'] });

  // UC3 step 2: the ID is generated by the system.
  newPackage.packageId = await generateId('package');

  await newPackage.save();

  res.status(201).json({
    message: `Package ${newPackage.packageId} added successfully.`,
    package: newPackage,
  });
}

/**
 * List packages, newest first.
 * GET /api/packages
 */
export async function listPackages(req, res) {
  const packages = await Package.find().sort({ createdAt: -1 });
  res.json({ count: packages.length, packages });
}

/**
 * Fetch one package by its readable ID.
 * GET /api/packages/P00001
 */
export async function getPackage(req, res) {
  const found = await Package.findOne({
    packageId: req.params.packageId.toUpperCase(),
  });

  if (!found) {
    return res.status(404).json({
      error: 'Not found',
      message: `No package with id ${req.params.packageId}.`,
    });
  }

  res.json({ package: found });
}
